### ISSUE TITLE
Can we access also the content of the muxiu1997/traefik-github-oauth-server project

### ISSUE THREAD

**Issue by smariko** [MuXiu1997/traefik-github-oauth-plugin#21]
Hi,

It's all in the subject :).

Is it possible to have access to the github-oauth-server project ?

Thanks in advance

**Comment by MuXiu1997** [comment]
Hi,

Are you referring to this directory: [internal/app/traefik-github-oauth-server](https://github.com/MuXiu1997/traefik-github-oauth-plugin/tree/main/)?

**Comment by smariko** [comment]
Not really, this is the repository of the main plugin. I'm referring to the the project related to the below docker image:
muxiu1997/traefik-github-oauth-server
Are the source code, Dockerfile publicly accessible ?

**Comment by MuXiu1997** [comment]
The source code and Dockerfile for muxiu1997/traefik-github-oauth-server are both contained in this repository. The link to the Dockerfile is https://github.com/MuXiu1997/traefik-github-oauth-plugin/blob/main/Dockerfile.

The link to the main file of traefik-github-oauth-server is https://github.com/MuXiu1997/traefik-github-oauth-plugin/blob/main/cmd/traefik-github-oauth-server/traefik-github-oauth-server.go.
