### ISSUE TITLE
Add support for arm64 in published docker image

### ISSUE THREAD

**Issue by wurmr** [MuXiu1997/traefik-github-oauth-plugin#22]
Right now the Docker image is only built for amd64. Adding arm64 would allow those running on raspberry pis to use it.

Documentation can be found here on how to add a multi-platform build:
https://docs.docker.com/build/ci/github-actions/multi-platform/

**Comment by MuXiu1997** [comment]
Thank you for your suggestion. I tried using a ready-made goreleaser configuration file from another project to fulfill this requirement, and it seems to be working correctly. However, I haven't conducted thorough testing.
