### ISSUE TITLE
Header or path exclusion

### ISSUE THREAD

**Issue by deathart** [MuXiu1997/traefik-github-oauth-plugin#26]
Hello, first of all thank you for your plugin which works perfectly!

But I'm having a problem:

I put the middleware on one of my services, but I would like to exclude routes that contain /api/webhooks, in other words I want to disable the middleware if the route contains /api/webhooks.

Is it possible to add either a system with a header that allows the middleware to be bypassed or to add exclusion rules?

Merci beaucoup

**Comment by MuXiu1997** [comment]
The official middleware does not seem to provide a "include or exclude specific paths" feature, so I think using multiple routers directly to solve this issue may be more flexible. 
Here is a simple example:

```yml
labels:
  # ......
  # base router
  - "traefik.http.routers.app.service=app-service"
  - "traefik.http.routers.app.rule=Host(`example.com`)"
  - "traefik.http.routers.app.middlewares=app-github-oauth"
  - "traefik.http.routers.app.priority=1"
  - "traefik.http.middlewares.app-github-oauth.plugin.github-oauth.apiBaseUrl=http://traefik-github-oauth-server"
  - "traefik.http.middlewares.app-github-oauth.plugin.github-oauth.whitelist.logins[0]=MuXiu1997"

  # webhooks router
  - "traefik.http.routers.app-webhooks.service=app-service"
  - "traefik.http.routers.app-webhooks.rule=Host(`example.com`) && PathPrefix(`/api/webhooks`)"
  - "traefik.http.routers.app-webhooks.priority=2" # higher priority than the base router, so that the webhooks can be accessed without authentication
  # ......
```

If you have better suggestions, feel free to discuss them.

**Comment by deathart** [comment]
Ok so I've tried to follow your instructions, unfortunately when I do a POST curl to https://protainer.exemple.com/api/webhooks/123g213gffgd213dfg12gf1d2 it doesn't work and I always get a 401 code response with the message: `http: named cookie not present`.

Here are my labels I may have done something wrong

```yaml
labels:
      - "traefik.http.routers.portainer.rule=Host(`portainer.exemple.com`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portainer.entrypoints=web,websecure"
      - "traefik.http.routers.portainer.middlewares=forward-auth@file"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.priority=1"
      # Webhook
      - "traefik.http.routers.portainer-webhooks.service=portainer"
      - "traefik.http.routers.portainer-webhooks.rule=Host(`portainer.exemple.com`) && PathPrefix(`/api/webhooks`)"
      - "traefik.http.routers.portainer-webhooks.priority=2"
  ```

**Comment by deathart** [comment]
Oh, I found that I wasn't actually telling the portainer-webhooks routers to use my entrypoints. If other people have the problem here are my labels in full with the solution:

```yaml
      - "traefik.http.routers.portainer.rule=Host(`portainer.exemple.com`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portainer.entrypoints=web,websecure"
      - "traefik.http.routers.portainer.middlewares=forward-auth@file"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.priority=1"
      # Webhook
      - "traefik.http.routers.portainer-webhooks.service=portainer"
      - "traefik.http.routers.portainer-webhooks.rule=Host(`portainer.exemple.com`) && PathPrefix(`/api/webhooks`)"
      - "traefik.http.routers.portainer-webhooks.tls=true"
      - "traefik.http.routers.portainer-webhooks.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portainer-webhooks.entrypoints=web,websecure"
      - "traefik.http.routers.portainer-webhooks.priority=2"
```

Thank you very much @MuXiu1997

**Comment by MuXiu1997** [comment]
This is a small test I just did, which demonstrates that this solution is feasible.

```shell
docker run --rm -it --network=proxy --name whoami \
    -l 'traefik.http.routers.r1.rule=Host(`test.docker.localhost`)' \
    -l 'traefik.http.routers.r1.service=s1' \
    -l 'traefik.http.routers.r1.priority=1' \
    -l 'traefik.http.routers.r2.rule=Host(`test.docker.localhost`)  && PathPrefix(`/webhooks`)' \
    -l 'traefik.http.routers.r2.service=s1' \
    -l 'traefik.http.routers.r2.middlewares=testHeader' \
    -l 'traefik.http.routers.r2.priority=2' \
    -l 'traefik.http.middlewares.testHeader.headers.customrequestheaders.X-Script-Name=test' \
    -l 'traefik.http.services.s1.loadbalancer.server.port=80' \
    traefik/whoami
```

```shell
$ curl http://test.docker.localhost/foo

Hostname: 630b6f06a179
IP: 127.0.0.1
IP: 172.22.0.3
RemoteAddr: 172.22.0.2:51002
GET /foo HTTP/1.1
Host: test.docker.localhost
User-Agent: curl/8.1.2
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 192.168.65.1
X-Forwarded-Host: test.docker.localhost
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 6f48a15aa147
X-Real-Ip: 192.168.65.1
```

```shell
$ curl http://test.docker.localhost/webhooks

Hostname: 630b6f06a179
IP: 127.0.0.1
IP: 172.22.0.3
RemoteAddr: 172.22.0.2:51002
GET /webhooks HTTP/1.1
Host: test.docker.localhost
User-Agent: curl/8.1.2
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 192.168.65.1
X-Forwarded-Host: test.docker.localhost
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 6f48a15aa147
X-Real-Ip: 192.168.65.1
X-Script-Name: test
```

You should probably keep the properties of routers consistent, except for the middlewares part. For example, you can try the following:

```yaml
labels:
  - "traefik.http.routers.portainer.rule=Host(`portainer.exemple.com`)"
  - "traefik.http.routers.portainer.tls=true"
  - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
  - "traefik.http.routers.portainer.entrypoints=web,websecure"
  - "traefik.http.routers.portainer.middlewares=forward-auth@file"
  - "traefik.http.routers.portainer.service=portainer"
  - "traefik.http.routers.portainer.priority=1"
  # Webhook
  - "traefik.http.routers.portainer-webhooks.rule=Host(`portainer.exemple.com`) && PathPrefix(`/api/webhooks`)"
  - "traefik.http.routers.portainer-webhooks.tls=true"
  - "traefik.http.routers.portainer-webhooks.tls.certresolver=letsencrypt"
  - "traefik.http.routers.portainer-webhooks.entrypoints=web,websecure"
  - "traefik.http.routers.portainer-webhooks.service=portainer"
  - "traefik.http.routers.portainer-webhooks.priority=2"
```
Did you send an HTTPS request that was handled by routers.portainer because your configuration didn't have TLS configured for routers.portainer-webhooks?

**Comment by MuXiu1997** [comment]
> Oh, I found that I wasn't actually telling the portainer-webhooks routers to use my entrypoints. If other people have the problem here are my labels in full with the solution:
> 
> ```yaml
>       - "traefik.http.routers.portainer.rule=Host(`portainer.exemple.com`)"
>       - "traefik.http.routers.portainer.tls=true"
>       - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
>       - "traefik.http.routers.portainer.entrypoints=web,websecure"
>       - "traefik.http.routers.portainer.middlewares=forward-auth@file"
>       - "traefik.http.routers.portainer.service=portainer"
>       - "traefik.http.routers.portainer.priority=1"
>       # Webhook
>       - "traefik.http.routers.portainer-webhooks.service=portainer"
>       - "traefik.http.routers.portainer-webhooks.rule=Host(`portainer.exemple.com`) && PathPrefix(`/api/webhooks`)"
>       - "traefik.http.routers.portainer-webhooks.tls=true"
>       - "traefik.http.routers.portainer-webhooks.tls.certresolver=letsencrypt"
>       - "traefik.http.routers.portainer-webhooks.entrypoints=web,websecure"
>       - "traefik.http.routers.portainer-webhooks.priority=2"
> ```
> 
> Thank you very much @MuXiu1997

👍 @deathart
